name: Build APK Club
on:
  push:
    branches: [ main ] # Déclenche le build dès que tu pousses ton code sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout du projet
        uses: actions/checkout@v3

      - name: 🟢 Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ☕ Configuration de Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🚀 Configuration de EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }} # Ton jeton Expo pour lier ton compte

      - name: 📦 Dépendances
        run: npm install

      - name: 🛠 Compilation de l'APK (Preview)
        run: eas build --platform android --profile preview --non-interactive