name: Déploiement Web PWA

on:
  push:
    branches:
      - code-source

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation
        run: npm ci --legacy-peer-deps

      - name: 🚀 Build
        run: npx expo export --platform web --clear

      - name: 🛠️ Correction des chemins (Injection de basePath)
        run: |
          # 1. Création du fichier .nojekyll pour que GitHub ne supprime pas les dossiers _expo
          touch dist/.nojekyll
          # 2. Correction du index.html pour pointer vers le sous-dossier
          sed -i 's|src="/_expo|src="/app-us-belleu/_expo|g' dist/index.html
          sed -i 's|href="/_expo|href="/app-us-belleu/_expo|g' dist/index.html
          # 3. Correction des fichiers JS pour qu'ils sachent où charger les chunks
          find dist/_expo/static/js -name "*.js" -exec sed -i 's|/_expo|/app-us-belleu/_expo|g' {} +

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: 🌐 Déploiement
        uses: actions/deploy-pages@v4