name: Déploiement Web PWA

on:
  push:
    branches:
      - code-source

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation
        run: npm ci --legacy-peer-deps

      - name: 🚀 Build
        run: npx expo export --platform web --clear

      - name: 🛠️ Setup GitHub Pages Compatibility
        run: |
          # Création du 404.html pour les routes SPA
          cp dist/index.html dist/404.html
          # Création du fichier .nojekyll pour éviter que GitHub ne supprime le dossier _expo
          touch dist/.nojekyll

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: 🌐 Déploiement
        uses: actions/deploy-pages@v4