name: Déploiement Web PWA

on:
  push:
    branches:
      - code-source

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm ci --legacy-peer-deps

      - name: 🚀 Compilation du site Web Expo
        run: npx expo export --platform web --clear
        env:
          EXPO_PUBLIC_BASE_URL: "/app-us-belleu/"

      # Étape cruciale pour le mode statique sur GitHub Pages
      - name: Préparation du dossier pour SPA
        run: cp dist/index.html dist/404.html

      # Utilisation de l'outil officiel d'upload d'artefact
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      # Utilisation de l'outil officiel de déploiement
      - name: 🌐 Déploiement sur GitHub Pages
        uses: actions/deploy-pages@v4